import Head from "next/head"
import About from "../components/About"
import Book from "../components/Book"
import Hero from "../components/Hero"
import More from "../components/More"
import Navbar from "../components/Navbar"

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Hope Counselling</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="">
        <Navbar />
        <Hero />
        <About />
        <More />
        <Book />
      </div>
    </div>
  )
}
